# Generated by Django 4.2.1 on 2023-05-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(
                choices=[
                    ("SR", "Server"),
                    ("CK", "Cook"),
                    ("DH", "Dishwasher"),
                    ("HH", "Host/Hostess"),
                    ("MG", "Manager"),
                    ("BT", "Bartender"),
                ],
                default="CK",
                max_length=2,
            ),
        ),
    ]
